DEVELOPMENT: false
LOGGING: false
USE_SHIM: false
EMBEDLY_ENDPOINT: "https://embedly-proxy.services.mozilla.com/v2/extract"
SENTRY_DSN: "https://8f7472f5a012407e9056a886648e91fd@sentry.prod.mozaws.net/150"
